# Generated by Django 6.1 on 2026-09-01 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leases', '0001_initial'),
        ('payments', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('LEASE_EXPIRY_30D', 'Lease expiry – 30 days before'), ('LEASE_EXPIRY_7D', 'Lease expiry – 7 days before'), ('LEASE_EXPIRY_DAY', 'Lease expiry – on expiry day'), ('LEASE_EXPIRY_7D_AFTER', 'Lease expiry – 7 days after'), ('LEASE_EXPIRY_14D_AFTER', 'Lease expiry – 14 days after'), ('LEASE_EXPIRY_21D_AFTER', 'Lease expiry – 21 days after'), ('LEASE_EXPIRY_28D_AFTER', 'Lease expiry – 28 days after'), ('RENT_UPCOMING_7D', 'Rent due – 7 days before'), ('RENT_UPCOMING_3D', 'Rent due – 3 days before'), ('RENT_DUE_DAY', 'Rent due – due date'), ('RENT_OVERDUE_3D', 'Rent overdue – 3 days'), ('RENT_OVERDUE_7D', 'Rent overdue – 7 days'), ('RENT_OVERDUE_14D', 'Rent overdue – 14 days'), ('INVITATION_SENT', 'Invitation sent'), ('INVITATION_ACCEPTED', 'Invitation accepted'), ('GENERAL', 'General')], max_length=40)),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('IN_APP', 'In-app')], default='IN_APP', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
                ('idempotency_key', models.CharField(db_index=True, max_length=300, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invitation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='tenants.tenantinvitation')),
                ('lease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='leases.lease')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='payments.payment')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx'), models.Index(fields=['recipient', 'notification_type'], name='notificatio_recipie_028906_idx'), models.Index(fields=['status', 'scheduled_for'], name='notificatio_status_d8d933_idx')],
            },
        ),
    ]
