# Generated by Django 5.2.17 on 2026-09-04 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('payments', '0002_remove_rentschedule_payment_add_payment_rent_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='rent_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='payments.rentschedule'),
        ),
    ]
