# Generated by Django 5.2.17 on 2026-09-04 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_seed_free_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='billing_cycle',
            field=models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('ANNUALLY', 'Annually')], default='MONTHLY', max_length=20),
        ),
        migrations.AddField(
            model_name='subscription',
            name='cancel_reason',
            field=models.TextField(blank=True),
        ),
    ]
