"""Notification domain models.

Email and in-app notifications. Scheduled reminders are executed by a
background management command (run via a process scheduler / cron).
Idempotency is enforced by a unique constraint on the idempotency key
(lease + event type + scheduled date window).
"""

from django.conf import settings
from django.db import models


class NotificationType(models.TextChoices):
    LEASE_EXPIRY_30D = 'LEASE_EXPIRY_30D', 'Lease expiry – 30 days before'
    LEASE_EXPIRY_7D = 'LEASE_EXPIRY_7D', 'Lease expiry – 7 days before'
    LEASE_EXPIRY_DAY = 'LEASE_EXPIRY_DAY', 'Lease expiry – on expiry day'
    LEASE_EXPIRY_7D_AFTER = 'LEASE_EXPIRY_7D_AFTER', 'Lease expiry – 7 days after'
    LEASE_EXPIRY_14D_AFTER = 'LEASE_EXPIRY_14D_AFTER', 'Lease expiry – 14 days after'
    LEASE_EXPIRY_21D_AFTER = 'LEASE_EXPIRY_21D_AFTER', 'Lease expiry – 21 days after'
    LEASE_EXPIRY_28D_AFTER = 'LEASE_EXPIRY_28D_AFTER', 'Lease expiry – 28 days after'
    RENT_UPCOMING_7D = 'RENT_UPCOMING_7D', 'Rent due – 7 days before'
    RENT_UPCOMING_3D = 'RENT_UPCOMING_3D', 'Rent due – 3 days before'
    RENT_DUE_DAY = 'RENT_DUE_DAY', 'Rent due – due date'
    RENT_OVERDUE_3D = 'RENT_OVERDUE_3D', 'Rent overdue – 3 days'
    RENT_OVERDUE_7D = 'RENT_OVERDUE_7D', 'Rent overdue – 7 days'
    RENT_OVERDUE_14D = 'RENT_OVERDUE_14D', 'Rent overdue – 14 days'
    INVITATION_SENT = 'INVITATION_SENT', 'Invitation sent'
    INVITATION_ACCEPTED = 'INVITATION_ACCEPTED', 'Invitation accepted'
    GENERAL = 'GENERAL', 'General'


class NotificationChannel(models.TextChoices):
    EMAIL = 'EMAIL', 'Email'
    IN_APP = 'IN_APP', 'In-app'


class NotificationStatus(models.TextChoices):
    PENDING = 'PENDING', 'Pending'
    SENT = 'SENT', 'Sent'
    FAILED = 'FAILED', 'Failed'
    CANCELLED = 'CANCELLED', 'Cancelled'


class Notification(models.Model):
    """A persisted notification event. The idempotency key prevents duplicate
    sends even when a scheduled job runs more than once."""

    recipient = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
        related_name='notifications',
    )
    notification_type = models.CharField(
        max_length=40, choices=NotificationType.choices,
    )
    channel = models.CharField(
        max_length=20, choices=NotificationChannel.choices,
        default=NotificationChannel.IN_APP,
    )
    status = models.CharField(
        max_length=20, choices=NotificationStatus.choices,
        default=NotificationStatus.PENDING,
    )

    # Related resources (nullable - general notifications may have none).
    # SET_NULL preserves the notification history even if the referenced
    # financial/tenancy record is later removed, so history is not silently
    # destroyed by a cascade.
    lease = models.ForeignKey(
        'leases.Lease', null=True, blank=True,
        on_delete=models.SET_NULL, related_name='notifications',
    )
    payment = models.ForeignKey(
        'payments.Payment', null=True, blank=True,
        on_delete=models.SET_NULL, related_name='notifications',
    )
    invitation = models.ForeignKey(
        'tenants.TenantInvitation', null=True, blank=True,
        on_delete=models.SET_NULL, related_name='notifications',
    )

    title = models.CharField(max_length=200)
    message = models.TextField()
    scheduled_for = models.DateTimeField(null=True, blank=True)
    sent_at = models.DateTimeField(null=True, blank=True)
    error_message = models.TextField(blank=True)

    # Read flag for in-app notifications only.
    is_read = models.BooleanField(default=False)

    # Deterministic idempotency key (lease/type/scheduled date window),
    # generated by the notification service/scheduler - never client-supplied.
    # The unique constraint prevents duplicate sends even if a scheduled job
    # runs more than once.
    idempotency_key = models.CharField(max_length=300, unique=True, db_index=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_at']
        indexes = [
            models.Index(fields=['recipient', 'is_read']),
            models.Index(fields=['recipient', 'notification_type']),
            models.Index(fields=['status', 'scheduled_for']),
        ]

    def __str__(self):
        return f'{self.notification_type} → {self.recipient.email} [{self.status}]'
