# Generated by Django 6.1 on 2026-09-02 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0002_alter_lease_status'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentschedule',
            name='payment',
        ),
        migrations.AddField(
            model_name='payment',
            name='rent_period',
            field=models.ForeignKey(blank=True, help_text='The rent obligation this payment targets.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='payments.rentschedule'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['rent_period', 'status'], name='payments_pa_rent_pe_9700fd_idx'),
        ),
    ]
