# Generated by Django 6.1 on 2026-09-11 08:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0003_remove_lease_lease_rent_due_day_range_and_more'),
        ('payments', '0002_remove_rentschedule_payment_add_payment_rent_period'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='idempotency_key',
            field=models.CharField(blank=True, help_text='Client-generated key making POST /payments idempotent.', max_length=64, null=True),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(fields=('landlord', 'idempotency_key'), name='uniq_landlord_idempotency_key'),
        ),
    ]
