# Generated by Django 6.1 on 2026-09-01 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('rent_frequency', models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('BI_ANNUALLY', 'Bi-annually'), ('ANNUALLY', 'Annually')], default='MONTHLY', max_length=20)),
                ('rent_due_day', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRING', 'Expiring'), ('EXPIRED', 'Expired'), ('TERMINATED', 'Terminated')], default='ACTIVE', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('terminated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('landlord', models.ForeignKey(limit_choices_to={'role': 'LANDLORD'}, on_delete=django.db.models.deletion.CASCADE, related_name='landlord_leases', to=settings.AUTH_USER_MODEL)),
                ('previous_lease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewals', to='leases.lease')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leases', to='properties.property')),
                ('tenant', models.ForeignKey(limit_choices_to={'role': 'TENANT'}, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_leases', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leases', to='properties.unit')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['landlord', 'status'], name='leases_leas_landlor_145517_idx'), models.Index(fields=['tenant', 'status'], name='leases_leas_tenant__9c2189_idx'), models.Index(fields=['unit', 'start_date', 'expiry_date'], name='leases_leas_unit_id_2591d8_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('expiry_date__gte', models.F('start_date'))), name='lease_expiry_after_start'), models.CheckConstraint(condition=models.Q(('currency__regex', '^[A-Z]{3}$')), name='lease_currency_iso3'), models.CheckConstraint(condition=models.Q(('rent_due_day__gte', 1), ('rent_due_day__lte', 28)), name='lease_rent_due_day_range'), models.CheckConstraint(condition=models.Q(('rent_amount__gte', 0)), name='lease_rent_amount_non_negative')],
            },
        ),
    ]
