# Generated by Django 6.1 on 2026-09-01 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='status',
            field=models.CharField(choices=[('FUTURE', 'Future'), ('ACTIVE', 'Active'), ('EXPIRING', 'Expiring'), ('EXPIRED', 'Expired'), ('TERMINATED', 'Terminated')], default='ACTIVE', max_length=20),
        ),
    ]
