# Generated by Django 5.2.17 on 2026-09-04 07:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0002_alter_lease_status'),
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='lease',
            name='lease_rent_due_day_range',
        ),
        migrations.AddConstraint(
            model_name='lease',
            constraint=models.CheckConstraint(condition=models.Q(('rent_due_day__gte', 1), ('rent_due_day__lte', 31)), name='lease_rent_due_day_range'),
        ),
    ]
