# Generated by Django 6.1 on 2026-09-11 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Key')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_token', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Token',
                'verbose_name_plural': 'Tokens',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='DeviceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=64)),
                ('device_name', models.CharField(default='', max_length=100)),
                ('refresh_token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('previous_refresh_token_hash', models.CharField(blank=True, default='', max_length=64)),
                ('refresh_expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(default='', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_sessions', to=settings.AUTH_USER_MODEL)),
                ('access_token', models.OneToOneField(blank=True, help_text='Short-lived access token for this device. Deleted on expiry/logout.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_session', to='core.token')),
            ],
            options={
                'ordering': ['-last_used_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'device_id'), name='uniq_user_device_session')],
            },
        ),
    ]
